### ISSUE TITLE
Add libzmq.so dependency

### ISSUE THREAD

**Issue by jackorp** [fedora-distgit/rubygem-ffi-rzmq-core#1]
The rubygem-ffi-rzmq-core depends on dynamic library `libzmq.so` specifically, both in runtime and in tests.

I see 3 solutions:
  * `Requires: pkgconfig(libzmq)`
  * `Requires: %{_libdir}/libzmq.so`
  * `Requires: zeromq` - this approach also requires patching into the source code the soname version to the library.

**Comment by pvalena** [comment]
https://github.com/fedora-distgit/rubygem-ffi-rzmq-core/blob/rawhide/rubygem-ffi-rzmq-core.spec#L12

**Comment by jackorp** [comment]
I made a [commit](https://github.com/fedora-distgit/rubygem-ffi-rzmq-core/commit/264a56e384bd7a650747591e1692d4d082cef922) specifying the soname version in the ruby package, so we can simply use the `zeromq` package as the dependency.

Not sure if this should be reported upstream, from what I gathered from looking at source code, they are trying to be flexible with not specifying soname version.

@pvalena What does [this line](https://github.com/fedora-distgit/rubygem-ffi-rzmq-core/blob/rawhide/rubygem-ffi-rzmq-core.spec#L58) do? It does not seem that it finds anything, at least from what I can see in the logs.

**Comment by jackorp** [comment]
Review request sent: [rhbz#1935650](https://bugzilla.redhat.com/show_bug.cgi?id=1935650)

**Comment by pvalena** [comment]
> @pvalena What does [this line](https://github.com/fedora-distgit/rubygem-ffi-rzmq-core/blob/rawhide/rubygem-ffi-rzmq-core.spec#L58) do? It does not seem that it finds anything, at least from what I can see in the logs.

That means there's no `*.so` file. I don't think you're building the extension then. And if there's no binary extension, it can be `noarch` package, like it originally was.

**Comment by jackorp** [comment]
It is noarch in the review request. And it does not build anything since it just loads and wraps dynamic libzmq library.

**Comment by pvalena** [comment]
Let's move the discussion to the Review Request. Thanks for creating it!
